version: '3'

networks:
    nginx-php74-mysql8-node:

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - ./app:/var/www/project
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php74-service
            - db
        networks:
            - nginx-php74-mysql8-node

    # php
    php74-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php74-container
        ports:
            - "9000:9000"
        volumes:
            - ./app:/var/www/project
        depends_on:
            - db
        networks:
            - nginx-php74-mysql8-node

    db:
        image: mariadb:10.3
        restart: always
        environment:
            MYSQL_DATABASE: journal
            MYSQL_USER: test
            MYSQL_PASSWORD: 1111
            MYSQL_ROOT_PASSWORD: rootpass
        networks:
            - nginx-php74-mysql8-node


    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - "1234:80"
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: db
        networks:
            - nginx-php74-mysql8-node
